export const ERROR_CODES = {
  INVALID_USERNAME: "INVALID_USERNAME",
  INVALID_PET: "INVALID_PET",
  INVALID_THEME: "INVALID_THEME",
  INVALID_EMOTION: "INVALID_EMOTION",
  RENDER_FAILED: "RENDER_FAILED"
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
